// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Creation is the predicate function for creation builders.
type Creation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
