// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Comment: "19 位雪花 ID"},
		{Name: "created_by", Type: field.TypeInt64, Comment: "创建者 ID", Default: 0},
		{Name: "updated_by", Type: field.TypeInt64, Comment: "更新者 ID", Default: 0},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时刻，带时区"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时刻，带时区"},
		{Name: "deleted_at", Type: field.TypeTime, Comment: "软删除时刻，带时区"},
		{Name: "name", Type: field.TypeString, Comment: "用户名", Default: "请设置昵称"},
		{Name: "nick_name", Type: field.TypeString, Comment: "用户昵称", Default: "请设置昵称"},
		{Name: "jpg_url", Type: field.TypeString, Comment: "头像", Default: ""},
		{Name: "phone", Type: field.TypeString, Comment: "用户的手机号", Default: ""},
		{Name: "password", Type: field.TypeString, Comment: "密码", Default: ""},
		{Name: "is_frozen", Type: field.TypeBool, Comment: "是否冻结", Default: false},
		{Name: "is_recharge", Type: field.TypeBool, Comment: "是否充值过", Default: false},
		{Name: "user_type", Type: field.TypeEnum, Comment: "用户类型", Enums: []string{"personal", "enterprise"}, Default: "personal"},
		{Name: "pop_version", Type: field.TypeString, Comment: "用户最新弹窗版本", Default: ""},
		{Name: "area_code", Type: field.TypeString, Comment: "国家区号", Default: "+86"},
		{Name: "email", Type: field.TypeString, Comment: "邮箱", Default: ""},
		{Name: "cloud_space", Type: field.TypeInt64, Comment: "云盘空间", Default: 0},
		{Name: "parent_id", Type: field.TypeInt64, Comment: "邀请人用户 id", Default: 0},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Comment:    "用户表",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
	UsersTable.Annotation = &entsql.Annotation{}
}
